### ISSUE TITLE
Pourquoi la license AGPL ?

### ISSUE THREAD

**Issue by bzg** [etalab/annuaire-entreprises-seo#2]
L'utilisation de la licence AGPL pour des codes sources qui relèvent du CRAP doit être justifiée d'une façon ou d'une autre.  Mais c'est peut-être juste une habitude contractée de l'époque où l'incubateur proposait cette licence par défaut ?  Le mieux est de partir sur une licence permissive comme les licences Expat (MIT), Apache 2.0 ou l'une des licences BSD.

A disposition pour aider si besoin.

**Comment by XavierJp** [comment]
Totalement une habitude, aujourd'hui la plupart des licences du projet Annuaire des Entreprises est AGPL.
- quelle license nous recommandes tu ? 
- quelles sont les étapes pour changer de licence ?

**Comment by bzg** [comment]
Merci pour la réponse !

Je recommande une MIT.  L'étape pour changer de licence est d'accepter la PR que je vais envoyer ☺️

**Comment by XavierJp** [comment]
Est ce que tu peux également faire une PR sur https://github.com/etalab/annuaire-entreprises-site ?

**Comment by bzg** [comment]
https://github.com/etalab/annuaire-entreprises-seo/pull/4
